@startuml
actor "User" as User
actor "Admin" as Admin

rectangle "Sistem Manajemen Toko Buku Online" {
    User --> (Login)
    User --> (Melihat Daftar Buku)

    Admin --> (Login)
    Admin --> (Melihat Daftar Buku)
    Admin --> (Menambahkan Buku)
    Admin --> (Mengubah Data Buku)
    Admin --> (Menghapus Buku)
}

@enduml